remote_read:
  - url: "http://127.0.0.1:9094/prometheus1/api/v1/read"

global:
  scrape_interval:     60s
  scrape_timeout:      10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s
    scrape_timeout:  1s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: pmm-server


  - job_name: grafana
    scrape_interval: 5s
    scrape_timeout:  4s
    static_configs:
      - targets: ['localhost:3000']
        labels:
          instance: pmm-server


  - job_name: linux
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['linux:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'

    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: pmm-server

  - job_name: proxysql
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['proxysql:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'


  - job_name: mongodb
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mongodb:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,cluster_([-\w:\.]+),.*'
      target_label:  'cluster'
      replacement:   '$1'


  - job_name: postgresql
    scrape_interval: 1s
    scrape_timeout:  1s
    metrics_path: /metrics
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['postgresql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'postgresql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mysql-hr
    scrape_interval: 1s
    scrape_timeout:  1s
    metrics_path: /metrics-hr
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'


  - job_name: mysql-mr
    scrape_interval: 5s
    scrape_timeout:  1s
    metrics_path: /metrics-mr
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'


  - job_name: mysql-lr
    scrape_interval: 60s
    scrape_timeout:   5s
    metrics_path: /metrics-lr
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_([\w]+),.*'
      target_label:  '__scheme__'
      replacement:   '$1'
