global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus


  - job_name: linux
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['linux:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'

    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: pmm-server


  - job_name: proxysql
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['proxysql:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mongodb
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mongodb:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,cluster_([-\w:\.]+),.*'
      target_label:  'cluster'
      replacement:   '$1'


  - job_name: mysql-hr
    metrics_path: /metrics-hr
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mysql-mr
    metrics_path: /metrics-mr
    scrape_interval:    5s
    scrape_timeout:     1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mysql-lr
    metrics_path: /metrics-lr
    scrape_interval:   60s
    scrape_timeout:     5s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'

